# Generated by Django 4.1.1 on 2022-09-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.SmallIntegerField(verbose_name='Código de verificação')),
                ('validade', models.DateField(verbose_name='Data de validade')),
                ('vencimento', models.PositiveSmallIntegerField(verbose_name='Dia do vencimento')),
                ('bandeira', models.CharField(choices=[('M', 'MasterCard'), ('E', 'Elo'), ('V', 'Visa')], max_length=1, verbose_name='Bandeira')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Limite')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('contato', models.CharField(max_length=10, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Saldo')),
                ('agencia', models.CharField(max_length=5, verbose_name='Agencia')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('tipo_de_conta', models.CharField(choices=[('CP', 'Conta Poupança'), ('CC', 'Conta Corrente'), ('CS', 'Conta Salario')], max_length=2, verbose_name='Tipo de conta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Em dia'), ('A', 'Em atraso')], default='D', max_length=1, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do empréstimo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Juros')),
                ('parcelas', models.SmallIntegerField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta', verbose_name='Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=30, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=30, verbose_name='Compemento')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('localidade', models.CharField(max_length=20, verbose_name='Localidade')),
                ('uf', models.CharField(max_length=20, verbose_name='UF')),
                ('num_casa', models.SmallIntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('valor_transacao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('beneficiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiado', to='home.conta', verbose_name='Beneficiado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='home.conta', verbose_name='Beneficiário')),
            ],
        ),
        migrations.CreateModel(
            name='Pag_emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da parcela')),
                ('data_pagamento', models.DateField(verbose_name='Data de pagamento')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.emprestimo', verbose_name='Emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctt_favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito', to='home.cliente', verbose_name='Favorito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='home.cliente', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fatura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(verbose_name='Pagamento')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cartao', verbose_name='Cartão')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Operação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta', verbose_name='Conta')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conta', verbose_name='Conta'),
        ),
    ]
