# Generated by Django 4.1.3 on 2022-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='bandeira',
            field=models.CharField(choices=[('Mastercard', 'MasterCard'), ('Elo', 'Elo'), ('Visa', 'Visa')], default='Visa', max_length=10, verbose_name='Bandeira'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo_de_conta',
            field=models.CharField(choices=[('CP', 'Conta Poupança'), ('CC', 'Conta Corrente'), ('CS', 'Conta Salario')], default='CC', max_length=2, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='operacao',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1, verbose_name='Operação'),
        ),
    ]
